# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f550e11069086887ea16b76de03536a2dafc0b7c6ea9b89b4b3936e60f0d597f61db4b630a67ea0b8ddc75aa6598082dfa228a4fc0df093aae8829c5423ae2f

test:
  secret_key_base: 64326c76863bb7638eeb0db7d913474019c91e6fdc1f19d79028605585d73c183fc9b77ba715e3a4c04fae4413b81c51632005d9e2a2e31361b990d51ad30297

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
